### ISSUE TITLE
Update release flow with speter555/gh-action-mvn-release-main@v0.27.0

### ISSUE THREAD

**Issue by speter555** [i-Cell-Mobilsoft-Open-Source/ticker-backend#5]
```
name: manual-RELEASE

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      comment:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Comment for release'
        # Default value if no value is explicitly provided
        default: 'Start release from WEB UI'
        # Input has to be provided for the workflow to run
        required: true
jobs:
  
  mvn-release:
    runs-on: ubuntu-latest
    # run only on main
    if: (github.ref_name == 'main' && contains('["rombow","czenczl","speter555"]', github.actor))
    
    steps:
      - name: Release
        uses: speter555/gh-action-mvn-release-main@v0.27.0
        with:
          ARTIFACT_STORE_SERVER_ID: 'ossrh'
          SETTINGS_XML_PATH: '.github/.m2/settings.xml'
          GPG_KEY_ID_GITHUB_TECHUSER: '${{ secrets.GPG_KEY_ID_GITHUB_TECHUSER }}'
          GPG_SIGNING_KEY_GITHUB_TECHUSER: '${{ secrets.GPG_SIGNING_KEY_GITHUB_TECHUSER }}'
          SSH_PRIVATE_KEY_GITHUB_TECHUSER: '${{ secrets.SSH_PRIVATE_KEY_GITHUB_TECHUSER }}'
          TECH_USER_USERNAME: 'icellmobilsoft-robot'
          TECH_USER_PASSWORD: '${{ secrets.OSS_SONATYPE_ORG_PASSWORD }}'
          TECH_USER_EMAIL: 'github_techuser@icellmobilsoft.hu'
          JAVA_VERSION: '17'
          JAVA_DISTRIBUTION: 'temurin'

```
